import torch

# TODO: expose as hyperparams
EPOCHS = 1000000
THRESHOLD = 1
DAMPING_FACTOR = 0.7
EPSILON = 1e-8
LEARNING_RATE = 0.00005
DEVICE = torch.device("mps")
SKIP_PROFILING = 1
DEFAULT_FOCUS_ITERATION_NEG_OFFSET = 1
DEFAULT_FOCUS_ITERATION_POS_OFFSET = 1
